FROM ghcr.io/gjuoun/alpine-node:16 as builder

WORKDIR /app

COPY . .

RUN pnpm i

RUN pnpm build

FROM ghcr.io/gjuoun/alpine-node:16 as runner

WORKDIR /app

COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json .
COPY --from=builder /app/dist/ ./dist

CMD ["pnpm", "start"]
